language: objective-c
xcode_sdk: iphonesimulator
before_install:
    - gem install xcpretty
script:
    - set -o pipefail
    - xcodebuild -workspace DLPhotoPickerDemo/DLPhotoPickerDemo.xcworkspace -scheme DLPhotoPickerDemo -sdk $TRAVIS_XCODE_SDK build | xcpretty
